server:
  port: 8090
  servlet:
    session:
      timeout: 10m
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: yusufbek200

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sirojiddinit@gmail.com
    password: cqcgezivhrsvqlor
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access:
    key: tHaX54Hwk^YMzKd@e@p7#70OZn0#D98BK8C1%T&hBnrzgqK28o
    expiration-time: 72000000
  refresh:
    key: tHaX54Hwk^YdfdsMzK-d@e@&p7#%70OZ()BK8C1%T&hBnrzgqK287
    expiration-time: 604800000
logging:
  file:
    name: codingbat.log
#  level:
#    org.springframework.web: ERROR
#    org.example: ERROR
#    org.hibernate: ERROR

app:
  admin:
    username: admin@codingbat.com
    password: root123
  upload:
    folder: /home/ubuntu/app-codingbat/
